### PR TITLE
[WIP] Embed Sinatra

### PR DESCRIPTION
**Pull request by lopopolo**
This branch is an ongoing effort to get the following code to parse and return a Rack app:

```ruby
require 'sinatra/base'

class MyApp < Sinatra::Base
  set :sessions, true
  set :foo, 'bar'

  get '/' do
    'Hello world!'
  end
end
```

This branch is a top-down approach to implementing core and the standard library in contrast to the bottom up approach I've been taking with Regexp.

The supplied main function in the `ditty` crate will return `MrbError` until the code parses and compiles. Address errors as they come up.

Some things I've had to do so far:

- Import Ruby sources for standard library components from Ruby 2.6.3.
- Modify Ruby standard library components for the mruby VM (e.g. Thread, Monitor, Mutex).
- Patch gem sources to work around [mruby limitations](https://github.com/mruby/mruby/blob/master/doc/limitations.md).

I anticipate needing to implement more of core and standard library in Rust.

### CODE REVIEW

**Comment by felipecsl** [comment]
solid 
)

**Comment by lopopolo** [comment]
`uri` depends on `String#scan`, which depends on `Regexp#match`.

Once I get a working Regexp matcher, I can implement scan in pure Ruby, using a string pointer. Here is the prototype:

https://github.com/lopopolo/ferrocarril/blob/37034d455d75d39eae4be5ffdd458de98713e42b/mruby-sys/vendor/mruby-c078758/mrblib/string.rb#L108-L116

**Comment by lopopolo** [comment]
GH-89 and GH-92 were extracted from this PR and added `Thread`, `Mutex`, and `Monitor` implementations.

**Comment by lopopolo** [comment]
As of 6368f9ff3e4ff2beae90b42ef4f204426bb94ec5, Sinatra is able to successfully load the `mustermann` gem. This requires a stub implementation of `StringScanner`. Implementing the required methods on `StringScanner` is tracked in GH-91.

**Comment by lopopolo** [comment]
As of this most recent push, the ditty crate successfully initializes a `Sinatra::Base` Rack application and returns a 404 page.

Screen Shot 2019-06-13 at 3 16 08 AM

(Showing the 404 page is a bug, but expected given the amount of stubbing going on.)

**Comment by lopopolo** [comment]
leak tests fail locally for me but seem to pass in CI. Will dig into this later.

**Comment by lopopolo** [comment]
Got an echo server running that outputs a JSON response containing the Rack request.

http://localhost:8000/boom succeeds
http://localhost:8000/boom?foo=bar blows up

**Comment by lopopolo** [comment]
Can't tell if this was GH-124 or GH-125, but the root page now renders and query string parsing works 🎉

**Comment by lopopolo** [comment]
It works!

Screen Shot 2019-06-21 at 3 36 09 PM

**Pull request merged**
